#!/usr/bin/env bash
# Install nginx on your web-01 server

sudo apt-get update 
sudo apt-get install -y nginx 

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default
# Restart nginx
sudo service nginx restart
