#!/usr/bin/env bash
# redirect nginx on your web-01 server

sudo apt-get update 
sudo apt-get install -y nginx 

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the editing access to the user
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup the default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creat a new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Create redirect link
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default


# Restart nginx
sudo service nginx restart
