#!/usr/bin/env bash
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 {start|stop|restart}"
  exit 1
fi

case "$1" in
start)
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;

  stop)
    [ -e "/var/run/my_process.pid" ] && pkill -f "./manage_my_process" && rm /var/run/my_process.pid
    echo "manage_my_process stopped"
    ;;

  restart)
    "$0" stop >& /dev/null
    "$0" start >& /dev/null
    echo "manage_my_process restarted"
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac