#!/usr/bin/env bash
# displays good luck for the 8th loop while Best School for others

a=1
while [ $a -le 10 ];
do
    if [ $a == 4 ];
    then
        echo "bad luck"
    elif [ $a == 8 ];
    then
	    echo "good luck"
    else
	echo "Best School"
    fi
    ((a++))
done